### ISSUE TITLE
error....

### ISSUE THREAD

**Issue by LeePC** [xsy822/mc-music-function#2]
C:\Users\akrrk\Documents\mc-music-function-2.0>music
480
track1
Traceback (most recent call last):
  File "music.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "midchange.py", line 106, in <module>
NameError: name 'program' is not defined
[3392] Failed to execute script music

**Comment by xsy822** [comment]
你是直接使用.exe文件得到的这个结果吗，可能是mid文件的问题，能把你使用的mid文件发给我吗

**Comment by LeePC** [comment]
yes


[touhou.zip](https://github.com/xsy822/mc-music-function/files/6175160/touhou.zip)

**Comment by xsy822** [comment]
I know why, you chose this mid file, there is a global track with notes in it, and I do not support reading the notes inside, and another track is missing the 'program' parameter, so it will be wrong

**Comment by xsy822** [comment]
Unfortunately, perhaps in the future my program will support files in this format

**Comment by xsy822** [comment]
Give you two mid files of music that I like very much, they can be used normally
[mid.zip](https://github.com/xsy822/mc-music-function/files/6175179/mid.zip)

**Comment by LeePC** [comment]
hm.....and......


https://user-images.githubusercontent.com/8704225/111865793-6eba1080-89ac-11eb-831c-5d580dabeb51.mp4

bug??

**Comment by xsy822** [comment]
Don't know where there is a problem, this song should be so fast, you need to press the flight, or you will fall down

**Comment by LeePC** [comment]
Tempo 120 BPM

**Comment by LeePC** [comment]
tested version 1.16.5
how to version??

**Comment by xsy822** [comment]
Version 1.13 or higher are available

**Comment by xsy822** [comment]
I like this song, too. Its Chinese name is the ’东方萃梦想‘, can you send me its mid file?

**Comment by LeePC** [comment]
https://musescore.com/user/13360806/scores/4023051

**Comment by LeePC** [comment]
[midi.zip](https://github.com/xsy822/mc-music-function/files/6175271/midi.zip)

**Comment by xsy822** [comment]
I know, a song usually has a mid-speed change, but my program does not support the change of speed, I choose the fastest speed, so there will be that kind of situation, should soon solve the problem

**Comment by xsy822** [comment]
I just found out that there's something wrong with the special effects of  'brokenLine', its time doesn't match the others

**Comment by LeePC** [comment]
https://discord.gg/yxGePU7ta8
redstone music discord room

**Comment by LeePC** [comment]
https://user-images.githubusercontent.com/8704225/111990003-d5c6f900-8b55-11eb-980f-2942cc516b5c.mp4

lag bug??
tested 1.16.5

**Comment by xsy822** [comment]
Color is the effect of modifying the mc source material file myself, and I don't know how to modify the particle material in the attach package

**Comment by xsy822** [comment]
Maybe you're too lag, or you can set the number of particles a little lower
